steps:
# Build and push backend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/restaurant-backend', './backend']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/restaurant-backend']

# Build and push frontend
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/restaurant-frontend', './frontend']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/restaurant-frontend']

# Build and push customer
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/restaurant-customer', './customer']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/restaurant-customer']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'run', 'services', 'replace', 'restaurant-service',
         '--region', 'us-central1',
         '--source', '.']
  env:
  - 'DB_PASSWORD=${_DB_PASSWORD}'

images:
- 'gcr.io/$PROJECT_ID/restaurant-backend'
- 'gcr.io/$PROJECT_ID/restaurant-frontend'
- 'gcr.io/$PROJECT_ID/restaurant-customer'

substitutions:
  _DB_PASSWORD: 'your-secure-password' 