name: Deploy to GCP

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Set up gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Authenticate Docker
    - name: Authenticate Docker
      run: |
        gcloud auth configure-docker

    # Build and push images
    - name: Build and push backend
      run: |
        docker build -t gcr.io/$PROJECT_ID/restaurant-backend ./backend
        docker push gcr.io/$PROJECT_ID/restaurant-backend

    - name: Build and push frontend
      run: |
        docker build -t gcr.io/$PROJECT_ID/restaurant-frontend ./frontend
        docker push gcr.io/$PROJECT_ID/restaurant-frontend

    - name: Build and push customer
      run: |
        docker build -t gcr.io/$PROJECT_ID/restaurant-customer ./customer
        docker push gcr.io/$PROJECT_ID/restaurant-customer

    # Deploy using docker-compose
    - name: Deploy to Cloud Run
      run: |
        gcloud run services replace ./docker-compose.prod.yml \
          --region=$REGION \
          --platform=managed \
          --allow-unauthenticated 